image: node:8.10.0

cache:
  paths:
    - code/client/node_modules/

stages:
  - lint
  - build
  - unittests

lint:
  stage: lint
  script:
    - cd code/client
    - npm install
    - ./node_modules/@angular/cli/bin/ng lint

build:
  stage: build
  script:
    - cd code/client
    - npm install
    - ./node_modules/@angular/cli/bin/ng build --prod --base-href ./

unittests:
  stage: unittests
  script:
    - cd code/server
    - npm install
    - npm start &
    - npm test ./tests
