image: node:8.10.0

cache:
  paths:
    - code/client/node_modules/

stages:
  - lint
  - build
  - expresstests
  - angulartests

# lint:
#   stage: lint
#   script:
#     - cd code/client
#     - npm install
#     - ./node_modules/@angular/cli/bin/ng lint

# build:
#   stage: build
#   script:
#     - cd code/client
#     - npm install
#     - ./node_modules/@angular/cli/bin/ng build --prod --base-href ./

# expresstests:
#   stage: expresstests
#   script:
#     - cd code/server
#     - npm install
#     - npm start &
#     - npm test ./tests

angulartests:
  variables:
    CLI_VERSION: 6.1.0
  stage: angulartests
  image: trion/ng-cli-karma:${CLI_VERSION}
  script:
    - cd code/client
    - npm install
    - ./node_modules/@angular/cli/bin/ng test --progress false --watch false